// client/src/components/SearchHeader.tsx
import { Button, Form, Input, PageHeader } from 'antd';
import React, { MutableRefObject, useCallback, useState } from 'react';
import { famousMovieTitles } from '../data/famousMovieTitles';
import { style } from '../utils/css';
import { goToRootPage } from '../utils/navigation';
import { random } from '../utils/number';

export interface ISearchHeaderProps {
  value?: string;
  hasBackButton?: boolean;
  onSubmit?: (value: string) => void;
  searchDisabled?: boolean;
  /** Callable function to set the value from outside */
  setValue?: MutableRefObject<(val: string) => void>;
}

const isEmpty = (text: string) => text.trim().length === 0;

function SearchForm(props: ISearchHeaderProps) {
  const [searchValue, setSearchValue] = useState(props.value ?? '');
  if (props.setValue)
    props.setValue.current = (val) => {
      console.log('inner event');
      setSearchValue(val);
    };

  const handleSubmit = useCallback(() => {
    if (!isEmpty(searchValue) && props.onSubmit) props.onSubmit(searchValue);
  }, [searchValue]);

  const randomMovieName = famousMovieTitles[random(famousMovieTitles.length - 1)];
  const isSubmitDisabled = isEmpty(searchValue) || props.searchDisabled;
  return (
    <Form layout="inline">
      <Form.Item label="Movie title">
        {/* ant does have an Input.Search, but the button part can not be disabled individually */}
        <Input
          placeholder={randomMovieName}
          disabled={props.searchDisabled}
          value={searchValue}
          onChange={(el) => setSearchValue(el.target.value)}
          onPressEnter={handleSubmit}
        />
      </Form.Item>
      <Form.Item>
        <Button type="primary" onClick={handleSubmit} disabled={isSubmitDisabled}>
          Search
        </Button>
      </Form.Item>
    </Form>
  );
}

export default function SearchHeader(props: ISearchHeaderProps) {
  const onBack = props.hasBackButton ? goToRootPage : undefined;
  return (
    <PageHeader
      title="Movies"
      onBack={onBack}
      subTitle="search for movies using tmdb and wikipedia"
      style={style.bgIndigo200}
      extra={<SearchForm {...props} />}
    />
  );
}

// 2023-01-biroda-vue/client/src/components/SearchHeader.vue
<script lang="ts" setup>
import { computed, onBeforeUpdate, ref } from 'vue';
import { getRandomItem } from '../utils/array';
import { famousMovieTitles } from '../data/famousMovieTitles';

const props = defineProps({
  urlQueryValue: String,
  searchDisabled: Boolean,
  onSubmit: Function,
  onBack: Function,
});

const searchValue = ref(props.urlQueryValue ?? '');
const randomMovieName = getRandomItem(famousMovieTitles);

// conditional event binding (ant page header @back is optional)
const atPageBackEventName = computed(() => (props.urlQueryValue !== '' ? 'back' : ''));

onBeforeUpdate(() => {
  // allow parent to send the value "down" (for example because the user modified the url manually)
  if (props.urlQueryValue !== searchValue.value) searchValue.value = props.urlQueryValue ?? '';
});

function handleSubmit() {
  if (searchValue && props.onSubmit) props.onSubmit(searchValue.value);
}
</script>
<!-- ====================================================================== -->
<template>
  <a-page-header
    title="Movies"
    @[atPageBackEventName]="onBack"
    subTitle="search for movies using tmdb and wikipedia"
    class="bg-indigo-200"
  >
    <!-- storm doesn't understand ant's slots or the slot has not been documented -->
    <template v-slot:extra>
      <!-- storm (probably ant's fault) thinks we have no inline layout type, but it's in the documentation -->
      <a-form layout="inline" @submit.prevent="handleSubmit">
        <a-form-item label="Movie title">
          <!-- ant needs v-model:value, plain v-model will not work -->
          <a-input v-model:value="searchValue" :placeholder="randomMovieName" :disabled="searchDisabled" />
        </a-form-item>
        <a-form-item>
          <!-- ant has a compact input group to group the button and the input, but an inline a-form-input will break that -->
          <a-button type="primary" html-type="submit" :disabled="!searchValue || searchDisabled">Search</a-button>
        </a-form-item>
      </a-form>
    </template>
  </a-page-header>
</template>
