// 2023-01-biroda/client/src/components/leftovers/SearchHeader.tsx
import { Button, Form, Input, PageHeader } from 'antd';
import React, { MutableRefObject, useCallback, useState } from 'react';
import { famousMovieTitles } from '../../data/famousMovieTitles';
import { style } from '../../utils/css';
import { goToRootPage } from '../../utils/navigation';
import { random } from '../../utils/number';

export interface ISearchHeaderProps {
  value?: string;
  hasBackButton?: boolean;
  onSubmit?: (value: string) => void;
  searchDisabled?: boolean;
  /** Callable function to set the value from outside */
  setValue?: MutableRefObject<(val: string) => void>;
}

const isEmpty = (text = '') => text.trim().length === 0;

function SearchForm(props: ISearchHeaderProps) {
  const [searchValue, setSearchValue] = useState(props.value ?? '');
  if (props.setValue)
    props.setValue.current = (val) => {
      setSearchValue(val);
    };

  const handleSubmit = useCallback(() => {
    if (!isEmpty(searchValue) && props.onSubmit) props.onSubmit(searchValue);
  }, [searchValue]);

  const randomMovieName = famousMovieTitles[random(famousMovieTitles.length - 1)];
  const isSubmitDisabled = isEmpty(searchValue) || props.searchDisabled;
  return (
    <Form layout="inline">
      <Form.Item label="Movie title">
        {/* ant does have an Input.Search, but the button part can not be disabled individually */}
        <Input
          placeholder={randomMovieName}
          disabled={props.searchDisabled}
          value={searchValue}
          onChange={(el) => setSearchValue(el.target.value)}
          onPressEnter={handleSubmit}
        />
      </Form.Item>
      <Form.Item>
        <Button type="primary" onClick={handleSubmit} disabled={isSubmitDisabled}>
          Search
        </Button>
      </Form.Item>
    </Form>
  );
}

export default function SearchHeader(props: ISearchHeaderProps) {
  const onBack = props.hasBackButton ? goToRootPage : undefined;
  return (
    <PageHeader
      title="Movies"
      onBack={onBack}
      subTitle="search for movies using tmdb and wikipedia"
      style={style.bgIndigo200}
      extra={<SearchForm {...props} />}
    />
  );
}

// 2023-01-biroda-vue/src/components/SearchHeader.vue
<script setup>
import { ref } from 'vue';
import { getRandomItem } from '../utils/array.ts';
import { famousMovieTitles } from '../data/famousMovieTitles.ts';

const props = defineProps({
  value: String,
  hasBackButton: Boolean,
  searchDisabled: Boolean,
  onSubmit: Function,
});

const searchValue = ref('');
const randomMovieName = getRandomItem(famousMovieTitles);

function handleSubmit() {
  if (searchValue && props.onSubmit) props.onSubmit(searchValue.value);
}
</script>
<template>
  <a-page-header
    title="Movies"
    subTitle="search for movies using tmdb and wikipedia"
    class="bgIndigo200"
  >
    <!-- storm doesn't understand ant's slots or the slot has not been documented -->
    <template v-slot:extra>
      <!-- storm (probably ant's fault) thinks we have no inline layout type, but it's in the documentation -->
      <a-form layout="inline" @submit.prevent="handleSubmit">
        <a-form-item label="Movie title">
          <!-- ant needs v-model:value, plain v-model will not work -->
          <a-input
            v-model:value.trim="searchValue"
            :placeholder="randomMovieName"
            :disabled="searchDisabled"
          />
        </a-form-item>
        <a-form-item>
          <!-- ant has a compact input group to group the button and the input, but an inline a-form-input will break that -->
          <a-button type="primary" html-type="submit" :disabled="!searchValue">Search</a-button>
        </a-form-item>
      </a-form>
    </template>
  </a-page-header>
</template>
