// 2023-01-biroda-vue/src/components/AppFooter.vue
<script setup>
import { famousQuotes } from '../data/famousQuotes';
import { random } from '../utils/number';

// we won't even need a ref here, it's just static text
const quote = famousQuotes[random(famousQuotes.length - 1)];
</script>
<template>
  <a-layout-footer class="italic textRight bgIndigo200">
    <a-typography-text>{{ quote.text }}</a-typography-text>
    {{ ' ' }}
    <a-typography-text type="secondary">{{ quote.author }}</a-typography-text>
  </a-layout-footer>
</template>

// 2023-01-biroda/client/src/components/leftovers/AppFooter.tsx
import { Footer } from 'antd/lib/layout/layout';
import Text from 'antd/lib/typography/Text';
import React from 'react';
import { famousQuotes } from '../../data/famousQuotes';
import { styles, style as st } from '../../utils/css';
import { random } from '../../utils/number';

export default function AppFooter() {
  const quote = famousQuotes[random(famousQuotes.length - 1)];
  return (
    <Footer style={styles(st.italic, st.textRight, st.bgIndigo200)}>
      <Text>{quote.text}</Text> <Text type="secondary">{quote.author}</Text>
    </Footer>
  );
}
