// 2023-01-biroda-vue/client/src/components/pages/searchResultsPage/DetailsModal.vue
<script lang="ts" setup>
import { computed, ref, watch } from 'vue';
import { useRouter } from 'vue-router';
import { getMovieById, IGetMovieByIdResponse } from '../../../api/getMovieById';
import { apiCall, ApiCallState } from '../../../utils/apiCall';
import CenterSpin from '../../common/CenterSpin.vue';
import CenterErrorMessage from '../../common/CenterErrorMessage.vue';

const router = useRouter();
const urlQuery = computed(() => String(router.currentRoute.value.query?.query ?? ''));
const urlId = computed(() => String(router.currentRoute.value.query?.id ?? ''));
const visible = computed(() => !!urlId.value);
const selectedId = ref('');
const result = ref<IGetMovieByIdResponse | undefined>();
const callState = ref(ApiCallState.Uninitialized);

// reset the modal, since we're not really destroying it
function handleCancel() {
  selectedId.value = '';
  result.value = undefined;
  callState.value = ApiCallState.Uninitialized;
  router.push({ query: { query: urlQuery.value, id: undefined } });
}

// watchEffect would be triggered by the routing, but since I'm fooling
// around on the same route, that would cause a trigger-happy behaviour
watch(
  urlId,
  () => {
    if (!urlId.value || urlId.value === selectedId.value) return;
    apiCall.toRefs(getMovieById(urlId.value), result, callState);
    selectedId.value = urlId.value;
  },
  { immediate: true }
);
</script>
<!-- ====================================================================== -->
<template>
  <a-modal :title="result?.title ?? '\xa0'" :visible="visible" width="800px" @ok="handleCancel" @cancel="handleCancel">
    <template #footer>
      <div class="flex gap-1 justify-end items-center">
        <template v-if="result">
          <a-typography-link :href="result?.wikipediaUrl" v-if="result.wikipediaUrl" target="_blank">
            Wikipedia
          </a-typography-link>
          <a-typography-link :href="result?.imdbUrl" v-if="result.imdbUrl" target="_blank">IMDB</a-typography-link>
        </template>
        <a-button @click="handleCancel" type="primary">Close</a-button>
      </div>
    </template>
    <!-- content -->
    <CenterSpin v-if="callState === ApiCallState.Pending" class="m-h-5" />
    <CenterErrorMessage v-if="callState === ApiCallState.Rejected" />
    <div v-if="callState === ApiCallState.Fulfilled" class="flex gap-2 z-1">
      <img :src="result?.poster" width="150" height="225" alt="Poster" class="poster" v-if="result?.poster" />
      <a-typography-paragraph>
        <a-typography-text>{{ result?.overview || 'Details are not available for this movie.' }}</a-typography-text>
        <br />
        <a-typography-text type="secondary">({{ result?.overviewSource }})</a-typography-text>
      </a-typography-paragraph>
    </div>
  </a-modal>
</template>
<!-- ====================================================================== -->
<style scoped>
.poster {
  border-radius: 5px;
  box-shadow: 0 2px 4px #aaa;
  border: 1px solid #fff;
}
</style>

// 2023-01-biroda/client/src/components/leftovers/DetailsModal.tsx
import { Button, Modal } from 'antd';
import Link from 'antd/lib/typography/Link';
import Text from 'antd/lib/typography/Text';
import React, { CSSProperties, useState } from 'react';
import { getMovieById, IGetMovieByIdResponse } from '../../api/getMovieById';
import { useLocationHash } from '../../hooks/useLocationHash';
import { apiCall, ApiCallState } from '../../utils/apiCall';
import { updateLocationHashParams } from '../../utils/navigation';
import CenterSpin from './CenterSpin';

const NBSP = '\xa0';
const linkStyle: CSSProperties = { marginRight: 10 };

// ant modal typedefinition is broken in this version and even if
// the proper issue exists, I still can't read the kanji :(
const BrokenModal = Modal as any; // eslint-disable-line @typescript-eslint/no-explicit-any

function ExternalLink({ text, url, key }: { text: string; url?: string; key: string }) {
  return url ? (
    <Link href={url} target="_blank" key={key} style={linkStyle}>
      {text}
    </Link>
  ) : null;
}

export default function DetailsModal() {
  const [callState, setCallState] = useState(ApiCallState.Uninitialized);
  const [result, setResult] = useState<IGetMovieByIdResponse | null>(null);
  const [selectedId, setSelectedid] = useState('');

  useLocationHash('id', (id?: string | number) => {
    setSelectedid(String(id ?? ''));
    if (id && id !== selectedId)
      apiCall.fromComponent<IGetMovieByIdResponse>(getMovieById(id), setResult, setCallState);
  });

  const handleCancel = () => {
    setResult(null);
    updateLocationHashParams('id', '');
  };

  const title = result?.title ?? NBSP;
  const wikipediaLink = (
    <ExternalLink url={result?.wikipediaUrl} text="Wikipedia" key="wikipediaLink" />
  );
  const imdbLink = <ExternalLink url={result?.imdbUrl} text="IMDB" key="imdbLink" />;
  const closeButton = (
    <Button onClick={handleCancel} type="primary" key="closeButton">
      Close
    </Button>
  );

  return (
    <BrokenModal
      title={title}
      visible={!!selectedId}
      cancelButtonProps={{ style: { display: 'none' } }}
      onCancel={handleCancel}
      onOk={handleCancel}
      footer={[wikipediaLink, imdbLink, closeButton]}
    >
      {callState === ApiCallState.Pending && <CenterSpin />}
      {callState === ApiCallState.Rejected && (
        <Text type="danger">
          Could not download movie details,
          <br />
          please try again later.
        </Text>
      )}
      {callState === ApiCallState.Fulfilled && (
        <>
          <Text>{result?.overview}</Text>
          <br />
          <Text type="secondary">({result?.overviewSource})</Text>
        </>
      )}
    </BrokenModal>
  );
}
