// 2023-01-biroda-vue/client/src/components/pages/searchResultsPage/SearchResultsTable.vue
<script lang="ts" setup>
import { formatDate } from '../../../utils/date';
import { getTableColumns } from '../../../utils/ant';
import { IMovieSearchResultItem } from '../../../api/getMovies';

const props = defineProps<{
  dataSource: IMovieSearchResultItem[];
  onItemClick: (id: number) => void;
  /** Comma delimited list of column names (affects the column order) */
  fields: string;
}>();

function getScoreTextType(score: number) {
  if (score > 80) return 'success';
  if (score < 20) return 'danger';
}

const columns = getTableColumns(props.dataSource, props.fields);
</script>
<!-- ====================================================================== -->
<template>
  <a-table :columns="columns" :dataSource="dataSource" rowKey="id" class="table m-1" v-if="dataSource">
    <template #bodyCell="{ column, record }">
      <template v-if="column.key === 'poster'">
        <img :src="record.poster" class="poster" v-if="record.poster" :alt="record.title" />
        <span class="poster" v-else></span>
      </template>
      <template v-if="column.key === 'title'">
        <a-button type="link" @click.prevent="onItemClick(record.id)" v-if="onItemClick">{{ record.title }}</a-button>
        <a-typography-text v-else>{{ record.title }}</a-typography-text>
      </template>
      <template v-if="column.key === 'score'">
        <a-typography-text :type="getScoreTextType(record.score)">{{ record.score }}</a-typography-text>
      </template>
      <template v-if="column.key === 'releaseDate'">
        <a-typography-text>{{ formatDate(record.releaseDate) }}</a-typography-text>
      </template>
      <template v-if="column.key === 'genres'">
        <a-tag v-for="genre in record.genres" :key="genre.id" :color="genre.color">{{ genre.name }}</a-tag>
      </template>
    </template>
  </a-table>
</template>
<!-- ====================================================================== -->
<style scoped>
.poster {
  width: 45px;
  height: 68px;
  background-color: #eee;
  border-radius: 2px;
  border: 1px solid #ddd;
  box-shadow: 0 2px 2px #eee;
  display: block;
}
/* since we need to pass the ant component boundary, we need the deep helper */
.table :deep(th) {
  text-transform: capitalize;
}
</style>

// 2022-04-biroda/client/src/components/SearchResultsTable.tsx
import { Button, Table, Tag } from 'antd';
import { ColumnsType } from 'antd/lib/table';
import { BaseType } from 'antd/lib/typography/Base';
import Text from 'antd/lib/typography/Text';
import React, { CSSProperties } from 'react';
import { IMovieGenre, IMovieSearchResultItem } from '../api/getMovies';

const imageStyle: CSSProperties = {
  width: 45,
  height: 68,
  backgroundColor: '#eee',
  border: '1px solid #ddd',
  display: 'block',
};

const getColumns = (
  onItemClick: ((id: number) => void) | undefined
): ColumnsType<IMovieSearchResultItem> => [
  {
    title: 'Poster',
    dataIndex: 'poster',
    key: 'poster',
    render: (url: string) =>
      url ? <img src={url} style={imageStyle} /> : <span style={imageStyle} />,
  },
  {
    title: 'Title',
    dataIndex: 'title',
    key: 'title',
    render: (title: string, item: IMovieSearchResultItem) => {
      return onItemClick ? (
        <Button type="link" onClick={() => onItemClick(item.id)}>
          {title}
        </Button>
      ) : (
        <Text>{title}</Text>
      );
    },
  },
  {
    title: 'Score',
    dataIndex: 'score',
    key: 'score',
    render: (score: number) => {
      let color: BaseType | undefined = undefined;
      if (score > 80) color = 'success';
      if (score < 20) color = 'danger';
      return <Text type={color}>{score}</Text>;
    },
  },
  {
    title: 'Release date',
    dataIndex: 'releaseDate',
    key: 'releaseDate',
  },
  {
    title: 'Genres',
    key: 'genres',
    dataIndex: 'genres',
    render: (genres: IMovieGenre[]) => (
      <>
        {genres.map((genre) => (
          <Tag key={genre.id} color={genre.color}>
            {genre.name}
          </Tag>
        ))}
      </>
    ),
  },
];

interface ISearchResultsTableProps {
  dataSource: IMovieSearchResultItem[];
  onItemClick?: (id: number) => void;
}

export default function SearchResultsTable(props: ISearchResultsTableProps) {
  const columns = getColumns(props.onItemClick);
  return (
    <Table columns={columns} dataSource={props.dataSource} rowKey="id" style={{ margin: 10 }} />
  );
}
